### ISSUE TITLE
issue with Spellchek.php. HTTP request fail while fetching translate.googlecom/*

### ISSUE THREAD

**Issue by athulrajdr** [subins2000/search#6] opened 2016-11-03 15:28 UTC
**Warning:** file_get_contents(http://translate.google.com/translate_a/t?client=t&sl=en&tl=en&hl=en&sc=2&ie=UTF-8&oe=UTF-8&uptl=en&oc=1&otf=1&ssel=3&tsel=0&q=c): failed to open stream: HTTP request failed! HTTP/1.0 403 Forbidden in **C:\xampp\htdocs\webcrawl\inc\spellcheck.php** on line **15**

**Comment by subins2000** [comment] 2016-11-04 02:37
The problem is Google blocked us from doing spell check. Hence the error.

**Comment by athulrajdr** [comment] 2016-11-05 12:01
in the last commit you have made some changes that to remove the dependency of google translate spellcheck by introducing **`inc/class.spellcheck.php`** in `/search.php` on line [`14`](https://github.com/subins2000/search/blob/master/search.php#L14). But there is no such file found the directory **`/inc/`**.

**Comment by subins2000** [comment] 2016-11-05 12:05
Fixed in commit https://github.com/subins2000/search/commit/ac90d8af9b541b467af20c17f2c7560f19610ee4

**Closed** 2016-11-05 14:34 UTC
